export type SpecialtyCategory = {
  id: string;
  label: string;
  specialties: string[];
};

/** Clinical specialties grouped for compact browsing during onboarding. */
export const therapistSpecialtyCategories: SpecialtyCategory[] = [
  {
    id: "mood",
    label: "Mood & Anxiety",
    specialties: [
      "Anxiety & Stress",
      "Generalized Anxiety",
      "Social Anxiety",
      "Panic Disorder",
      "Phobias",
      "Depression",
      "Bipolar Disorder",
      "Seasonal Affective Disorder",
      "Emotional Regulation",
      "Burnout",
      "Anger Management",
    ],
  },
  {
    id: "trauma",
    label: "Trauma & Crisis",
    specialties: [
      "Trauma & PTSD",
      "Complex Trauma (C-PTSD)",
      "Childhood Trauma",
      "Sexual Trauma",
      "Domestic Violence / IPV",
      "Crisis Intervention",
      "Suicide Prevention",
      "Self-Harm",
      "Grief & Loss",
      "Complicated Grief",
    ],
  },
  {
    id: "relationships",
    label: "Relationships & Family",
    specialties: [
      "Relationship Issues",
      "Couples Therapy",
      "Marriage Counseling",
      "Premarital Counseling",
      "Divorce & Separation",
      "Family Therapy",
      "Parenting Support",
      "Co-Parenting",
      "Blended Families",
      "Infidelity Recovery",
      "Attachment Issues",
      "Communication Skills",
    ],
  },
  {
    id: "identity",
    label: "Identity & Culture",
    specialties: [
      "LGBTQ+ Support",
      "Gender Identity",
      "Sexual Orientation",
      "Cultural Identity",
      "Racial Trauma",
      "Immigration & Acculturation",
      "Faith-Based Counseling",
      "Spiritual Concerns",
    ],
  },
  {
    id: "life-stages",
    label: "Life Stages",
    specialties: [
      "Child Therapy",
      "Adolescent / Teen Therapy",
      "Young Adults",
      "College / Student Mental Health",
      "Adult Therapy",
      "Midlife Transitions",
      "Geriatric / Older Adults",
      "Men's Mental Health",
      "Women's Mental Health",
      "Perinatal / Postpartum Mental Health",
      "Infertility Support",
      "Pregnancy Loss",
    ],
  },
  {
    id: "neuro",
    label: "Neurodiversity",
    specialties: [
      "ADHD",
      "Autism Spectrum",
      "Learning Differences",
      "Executive Functioning",
      "Neurodivergence Affirming Care",
    ],
  },
  {
    id: "behavioral",
    label: "Behavioral Health",
    specialties: [
      "Addiction Recovery",
      "Substance Use",
      "Alcohol Use",
      "Behavioral Addictions",
      "Gambling",
      "Internet / Gaming Addiction",
      "Eating Disorders",
      "Body Image",
      "Sleep Issues / Insomnia",
      "Chronic Pain",
      "Health Anxiety",
      "Psychosomatic Concerns",
    ],
  },
  {
    id: "clinical",
    label: "Clinical Conditions",
    specialties: [
      "Personality Disorders",
      "Borderline Personality (BPD)",
      "OCD",
      "Hoarding",
      "Psychosis / Schizophrenia Support",
      "Dissociative Disorders",
    ],
  },
  {
    id: "work",
    label: "Work & Performance",
    specialties: [
      "Career Counseling",
      "Workplace Stress",
      "Academic Stress",
      "Performance Anxiety",
      "Imposter Syndrome",
      "Life Coaching (Clinical)",
    ],
  },
  {
    id: "modalities",
    label: "Approaches & Modalities",
    specialties: [
      "Cognitive Behavioral Therapy (CBT)",
      "Dialectical Behavior Therapy (DBT)",
      "Acceptance & Commitment Therapy (ACT)",
      "EMDR",
      "Psychodynamic Therapy",
      "Humanistic / Person-Centered",
      "Solution-Focused Therapy",
      "Narrative Therapy",
      "Motivational Interviewing",
      "Mindfulness-Based Therapy",
      "Play Therapy",
      "Art Therapy",
      "Group Therapy",
      "Teletherapy / Online Counseling",
    ],
  },
  {
    id: "community",
    label: "Community & Context",
    specialties: [
      "Community Mental Health",
      "Peer Support Facilitation",
      "Stigma & Mental Health Advocacy",
      "School Counseling",
      "Employee Assistance (EAP)",
      "Forensic / Legal-Related Support",
      "Refugee & Displacement Support",
      "Poverty-Related Stress",
      "Caregiver Support",
      "Chronic Illness Adjustment",
      "HIV / Sexual Health Counseling",
    ],
  },
];

export const therapistSpecialties = therapistSpecialtyCategories.flatMap(
  (category) => category.specialties,
);
